server.port=8080
spring.application.name=ApiTurny

spring.datasource.url=jdbc:postgresql://localhost:5432/turny_db
spring.datasource.username=postgres
spring.datasource.password=1287985dbc
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.security.user.name=santiago
spring.security.user.password=1234

turny.jwt.secret=turny-super-secret-key-cambiame-en-prod
turny.jwt.expiration-ms=86400000

turny.cors.allowed-origins=*

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100